[cog] run fx-update-path before cog command
This change updates the fx wrapper script to patch the PATH correctly when we need to run builds in cog.

Change-Id: I3dc3606c4db8e470989ecb65c75370698d2c0c66
Reviewed-on: https://fuchsia-review.googlesource.com/c/fuchsia/+/1485536
Commit-Queue: Chase Latta <chaselatta@google.com>
Reviewed-by: Jiaming Li <lijiaming@google.com>
Fuchsia-Auto-Submit: Chase Latta <chaselatta@google.com>

diff --git a/scripts/cog/resources/fx b/scripts/cog/resources/fx
--- a/scripts/cog/resources/fx
+++ b/scripts/cog/resources/fx
@@ -7,6 +7,14 @@ FUCHSIA_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." >/dev/null 2>&1 && pwd)
 
 command="$1"
 if [[ "$command" =~ ^(set|build|test|add-test|add-host-test|set-main-pb)$ ]]; then
+  if [[ ! -L "${FUCHSIA_DIR}/cartfs-dir" || ! -e "${FUCHSIA_DIR}/cartfs-dir" ]]; then
+    echo "Error: unable to find the cartfs symlink. Run the setup script to fix this."
+    exit 1
+  fi
+  # We need to run this here to make sure that the PATH is updated with the
+  # prebuilts in the CartFS. If we do not do this then we will pick up the wrong
+  # hermetic-env.
+  source "${FUCHSIA_DIR}/cartfs-dir/fuchsia/scripts/fx-env.sh" && fx-update-path
   exec "${FUCHSIA_DIR}/scripts/fx" cog "$@"
 else
   exec "${FUCHSIA_DIR}/scripts/fx" "$@"
