[readme_fuchsia] Add readme_fuchsia as an fx command
And add helpful messages if the tool hasn't been compiled

Change-Id: I686fe58e78a8c54d4e66b11dd24559395d468933
Reviewed-on: https://fuchsia-review.googlesource.com/c/fuchsia/+/1676277
Reviewed-by: Steven Grady <slgrady@google.com>
Commit-Queue: Jerry Belton <jcecil@google.com>

diff --git a/tools/devshell/contrib/check-licenses b/tools/devshell/contrib/check-licenses
--- a/tools/devshell/contrib/check-licenses
+++ b/tools/devshell/contrib/check-licenses
@@ -15,5 +15,13 @@ fx-config-read
 
 export PREBUILT_3P_DIR HOST_PLATFORM
 
-"$(get_host_tools_dir)/check-licenses" "$@"
+BINARY="$(get_host_tools_dir)/check-licenses"
+if [[ ! -x "${BINARY}" ]]; then
+  fx-error "check-licenses binary not found."
+  echo "Please build it first by running:"
+  echo "    fx build --host //tools/check-licenses:host"
+  exit 1
+fi
+
+"${BINARY}" "$@"
 
