[tools] Add --no-wipe flag to flash-kola
Bug: 397515768
Test: Verified locally on device. Tested flashing from the Android
bootloader, 2nd stage bootloader, and userspace fastboot in recovery
both with and without the --no-wipe flag.

Depends-on: fuchsia:I2265d59b70def8d9364e9750cfdf6d887d552faf
Depends-on: turquoise-internal:Ice13efd2d59f473ee89b811fb7d60145cad63c99
Depends-on: turquoise-internal:I39edf0c87406d5a2c558027b03bf19472e3f58b3
Change-Id: Ib014d42cdf82cbdc8447647f9a95e5f3cec8f782
Reviewed-on: https://fuchsia-review.googlesource.com/c/fuchsia/+/1387009
Commit-Queue: Brandon Castellano <bcastell@google.com>
Reviewed-by: Prashanth Swaminathan <prashanthsw@google.com>
Reviewed-by: David Pursell <dpursell@google.com>
Dependencies-Satisfied: CL Deps Checker <cl-deps-checker@fuchsia-internal-service-accts.iam.gserviceaccount.com>

diff --git a/tools/devshell/contrib/flash-kola b/tools/devshell/contrib/flash-kola
--- a/tools/devshell/contrib/flash-kola
+++ b/tools/devshell/contrib/flash-kola
@@ -6,7 +6,7 @@
 #### CATEGORY=Other
 ### Flash Fuchsia onto a Kola board that has an unmodified bootloader.
 
-## usage: fx flash-kola
+## usage: fx flash-kola [--no-wipe]
 
 # Bash strict mode.
 set -eo pipefail
@@ -16,6 +16,26 @@ fx-config-read
 
 # Use the in-tree fastboot.
 readonly FASTBOOT="${FUCHSIA_DIR}/prebuilt/third_party/fastboot/fastboot"
+
+# When rebooting the device, we have to add a small delay to ensure the host actually drops the
+# device before the next fastboot command is executed. Without this delay, the next command may
+# execute before the host realizes the device is gone, causing the following command to fail.
+readonly DEVICE_REBOOT_DELAY=4
+
+if [[ $# -gt 1 ]]; then
+  fx-command-help
+  exit 1
+fi
+
+WIPE_USERDATA="yes"
+if [[ $# -eq 1 ]]; then
+  if [[ "$1" == "--no-wipe" ]]; then
+    WIPE_USERDATA="no"
+  else
+    fx-command-help
+    exit 1
+  fi
+fi
 
 
 # TODO(b/373727276): Change to use `ffx target flash` instead.
@@ -36,7 +56,12 @@ if [[ -d "${PRODUCT_BUNDLE}/system_r" ]]; then
   RECOVERY_PATH="${PRODUCT_BUNDLE}/$(fx-command-run jq --raw-output '.system_r[] | select(.name=="zircon-a") | .path' "${ARTIFACTS}")"
 fi
 
-readonly FVM_PATH ZBI_PATH DTBO_PATH RECOVERY_PATH
+readonly FVM_PATH ZBI_PATH DTBO_PATH RECOVERY_PATH WIPE_USERDATA
+
+if [[ "$WIPE_USERDATA" == "no" && -z "$RECOVERY_PATH" ]]; then
+  fx-error "The --no-wipe flag requires a recovery image for the product."
+  exit 1
+fi
 
 if [[ -z $ANDROID_SERIAL ]]; then
   readonly DEVICE_COUNT=$(${FASTBOOT} devices | awk NF | wc -l)
@@ -48,6 +73,8 @@ if [[ -z $ANDROID_SERIAL ]]; then
 fi
 
 BOOTLOADER="$(${FASTBOOT} getvar product 2>&1 | grep '^product:' | awk '{print $2}')"
+IS_USERSPACE="$(${FASTBOOT} getvar is-userspace 2>&1 | grep '^is-userspace:' | awk '{print $2}')"
+
 # Only attempt to set bootmode if the bootloader is not 'sorrel' and mode is not 'factory'
 if [[ "${BOOTLOADER}" != "sorrel" ]]; then
   # Ensure bootmode is set to factory before flashing partitions.
@@ -63,7 +90,7 @@ if [[ "${BOOTLOADER}" != "sorrel" ]]; then
   INITIAL_BOOTMODE="" # Initialize to empty
 
   if [[ ${BOOTMODE_EXIT_CODE} -eq 0 ]]; then
-    CURRENT_BOOTMODE=$(echo "${BOOTMODE_OUTPUT}" | awk '/bootmode:/ {print $3}')
+    readonly CURRENT_BOOTMODE=$(echo "${BOOTMODE_OUTPUT}" | awk '/bootmode:/ {print $3}')
     INITIAL_BOOTMODE="${CURRENT_BOOTMODE}" # Store the initial bootmode
     if [[ "${CURRENT_BOOTMODE}" != "factory" ]]; then
       fx-info "Current bootmode is '${CURRENT_BOOTMODE}', setting it to 'factory'."
@@ -78,7 +105,16 @@ if [[ "${BOOTLOADER}" != "sorrel" ]]; then
     fx-warn "Proceeding with flashing, but bootmode might not be 'factory'."
   fi
 else
-  fx-info "Bootloader is '${BOOTLOADER}'."
+  fx-info "Bootloader is '${BOOTLOADER}' (is-userspace: ${IS_USERSPACE})."
+fi
+
+readonly BOOTLOADER INITIAL_BOOTMODE IS_USERSPACE
+
+if [[ "${IS_USERSPACE}" == "yes" ]]; then
+  # If we started in userspace fastboot, go back to the bootloader to flash the boot partitions.
+  fx-info "Rebooting to bootloader from userspace fastboot"
+  ${FASTBOOT} reboot bootloader
+  sleep "${DEVICE_REBOOT_DELAY}" # Ensure host drops device before issuing next command.
 fi
 
 for PART_NAME in "${!BOOTLOADER_IMAGES[@]}"; do
@@ -93,17 +129,21 @@ if [[ -n "$RECOVERY_PATH" ]]; then
   ${FASTBOOT} flash vendor_boot_b "$RECOVERY_PATH"
 fi
 
-# Reboot back into the bootloader.
-# Some builds put firmware in the boot image, in which case we reboot here to
-# pick up the new firmware we just flashed. For builds that don't put firmware
-# in boot, this is still fine and just triggers a reboot now rather than at the
-# end of flashing.
-fx-info "Rebooting to bootloader"
-${FASTBOOT} reboot bootloader
-# Pause to make sure fastboot actually drops the device; sometimes without this
-# the next fastboot command will execute before the host realizes the device is
-# gone which causes the command to fail.
-sleep 4
+if [[ "$WIPE_USERDATA" == "no" ]]; then
+  fx-info "Rebooting into userspace fastboot"
+  ${FASTBOOT} reboot fastboot
+else
+  # Reboot back into the bootloader.
+  # Some builds put firmware in the boot image, in which case we reboot here to
+  # pick up the new firmware we just flashed. For builds that don't put firmware
+  # in boot, this is still fine and just triggers a reboot now rather than at the
+  # end of flashing.
+  fx-info "Rebooting to bootloader"
+  ${FASTBOOT} reboot bootloader
+fi
+
+sleep "${DEVICE_REBOOT_DELAY}" # Ensure host drops device before issuing next command.
+
 # Attempt to flash SSH keys. This is only supported on devices running custom
 # Fuchsia firmware, so if it doesn't work just log a warning.
 function push_ssh_keys {
@@ -126,7 +166,9 @@ function push_ssh_keys {
   }
 }
 
-if [[ "${BOOTLOADER}" == "sorrel" ]]; then
+if [[ "$WIPE_USERDATA" == "no" ]]; then
+  fx-info "Skipping provisioning of SSH keys because --no-wipe was specified."
+elif [[ "${BOOTLOADER}" == "sorrel" ]]; then
   if push_ssh_keys; then
     fx-info "Successfully provisioned SSH keys via bootloader"
   else
@@ -136,14 +178,33 @@ else
   fx-info "Skipping bootloader provisioning of SSH keys because bootloader is ${BOOTLOADER}"
 fi
 
-# Flash the super partition last; some Kola devices exhibit USB instability
-# after flashing large super partition data so we want to do as much as
-# possible before this while the USB is more reliable (b/405436515).
-${FASTBOOT} flash super "$FVM_PATH"
+if [[ "$WIPE_USERDATA" == "no" ]]; then
+  # Only flash the blob volume if we aren't wiping the data volume. This command only works from
+  # userspace fastboot. The volume will be installed when the device next reboots normally.
+  ${FASTBOOT} flash blob "$FVM_PATH"
+else
+  # Flash the super partition last; some Kola devices exhibit USB instability
+  # after flashing large super partition data so we want to do as much as
+  # possible before this while the USB is more reliable (b/405436515).
+  #
+  # *WARNING*: This command will irreversibly destroy all data on the device!
+  # This does not securely wipe the device, but all userdata will be lost.
+  ${FASTBOOT} flash super "$FVM_PATH"
+fi
 
 # Attempt to restore the initial bootmode if it was changed
 if [[ -n "${INITIAL_BOOTMODE}" && "${INITIAL_BOOTMODE}" != "factory" ]]; then
   fx-info "Attempting to restore initial bootmode to '${INITIAL_BOOTMODE}'..."
+  if [[ "$WIPE_USERDATA" == "no" ]]; then
+    # We flashed from userspace fastboot, go back to the bootloader to set the bootmode back.
+    ${FASTBOOT} reboot bootloader
+    sleep "${DEVICE_REBOOT_DELAY}" # Ensure host drops device before issuing next command.
+  fi
+  readonly CURRENT_BOOTLOADER="$(${FASTBOOT} getvar product 2>&1 | grep '^product:' | awk '{print $2}')"
+  if [[ "${CURRENT_BOOTLOADER}" == "sorrel" ]]; then
+    ${FASTBOOT} oem reboot-android-fastboot
+    sleep "${DEVICE_REBOOT_DELAY}" # Ensure host drops device before issuing next command.
+  fi
   # Check the exit status of the set_config command
   if ${FASTBOOT} oem set_config bootmode "${INITIAL_BOOTMODE}"; then
     fx-info "Successfully restored bootmode to '${INITIAL_BOOTMODE}'."
