[fx] exit early if we are running on macOS
This command has printed a deprecation warning for a reasonable amount
of time and is now being disabled.

Fixes: 419872734
Change-Id: I85ae0321e3cc69be84a2ccfbeb8e4c2e6a3414db
Reviewed-on: https://fuchsia-review.googlesource.com/c/fuchsia/+/1407154
Reviewed-by: Christopher Johnson <crjohns@google.com>
Reviewed-by: Andrew Davies <awdavies@google.com>
Commit-Queue: Chase Latta <chaselatta@google.com>

diff --git a/scripts/fx b/scripts/fx
--- a/scripts/fx
+++ b/scripts/fx
@@ -190,9 +190,10 @@ function find_tree_root {
   echo "$parent"
 }
 
-function show_mac_deprecation_warning {
+function check_running_on_supported_platform {
   if [[ "$(uname -s)" == "Darwin" ]]; then
-    fx-warn "This tool is deprecated per go/fuchsia-on-mac and will be removed on [2025/07/01]: b/419872734"
+    fx-error "This tool is no longer supported on macOS per go/fuchsia-on-mac."
+    exit 1
   fi
 }
 
@@ -379,8 +380,9 @@ while [[ $# -ne 0 ]]; do
   shift
 done
 
-# Show our mac deprecation before any other messages
-show_mac_deprecation_warning
+# Check if we are running on a supported platform. We currently do not support macOS
+# so this will fail if run on a macOS system.
+check_running_on_supported_platform
 
 if [[ $# -lt 1 ]]; then
   usage
